
#testpartition -n 4
#test_main
#reset_timer

read_blif /home/ymc/project/git/abc/ymc_test/blif/denoise.blif
#read_blif /home/ymc/buffer/paper_blif/raytracer.blif
pif /home/ymc/project/git/abc/ymc_test/lib9match.dsd
print_stats

#pif -n 32 /home/ymc/project/git/abc/ymc_test/lib9match.dsd
#print_time
#print_stats
#print_time

#dsd_load /home/ymc/project/git/abc/ymc_test/lib9.dsd
#dsd_ps -v -o
#dsd_load /home/ymc/project/git/abc/ymc_test/lib9filter.dsd
#dsd_ps -v -o
dsd_load /home/ymc/project/git/abc/ymc_test/lib9match.dsd
#dsd_ps -v -o


read_blif /home/ymc/project/git/abc/ymc_test/blif/denoise.blif
if -k -K 9
#dsd_ps -v -o
print_stats
#
#read_blif /home/ymc/project/git/abc/ymc_test/blif/cholesky.blif
#if -K 5
#print_stats
#
#read_blif /home/ymc/project/git/abc/ymc_test/blif/cholesky.blif
#if -K 6
#print_stats
#
#read_blif /home/ymc/project/git/abc/ymc_test/blif/cholesky.blif
#if -K 9
#print_stats